
module.exports = {
    fakeBoard: [
        { id: 1, host_name: "승현", location_name: "천안", date: "2019/11/1", participate: true },
        { id: 2, host_name: "승현", location_name: "부산", date: "2019/11/1", participate: false },
        { id: 4, host_name: "승현", location_name: "서울", date: "2019/11/1", participate: true },
        { id: 5, host_name: "승현", location_name: "대전", date: "2019/11/9", participate: false },
        { id: 6, host_name: "승현", location_name: "대구", date: "2019/11/10", participate: true },
        { id: 7, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: true },
        { id: 8, host_name: "승현", location_name: "충주", date: "2019/11/12", participate: true },
        { id: 9, host_name: "승현", location_name: "오산", date: "2019/11/14", participate: false },
        { id: 10, host_name: "승현", location_name: "세종", date: "2019/11/23", participate: true },
        { id: 11, host_name: "승현", location_name: "윤", date: "2019/11/23", participate: false },
        { id: 12, host_name: "승현", location_name: "세종", date: "2019/11/23", participate: true },
        { id: 13, host_name: "승현", location_name: "딥", date: "2019/11/23", participate: false },
        { id: 14, host_name: "승현", location_name: "세종", date: "2019/11/23", participate: true },
        { id: 15, host_name: "승현", location_name: "ㅊㅋㅌㅊ", date: "2019/11/23", participate: true },
        { id: 16, host_name: "승현", location_name: "세종", date: "2019/11/23", participate: false },
        { id: 17, host_name: "승현", location_name: "세ㅇㅁㅇ종", date: "2019/11/23", participate: true },
        { id: 18, host_name: "승현", location_name: "ㅇㅁㄴ", date: "2019/11/23", participate: false },
        { id: 19, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: false },
        { id: 20, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: true },
        { id: 21, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: false },
        { id: 22, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: true },
        { id: 23, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: false },
        { id: 24, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: false },
        { id: 25, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: true },
        { id: 26, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: false },
        { id: 27, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: false },
        { id: 28, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: false },
        { id: 29, host_name: "승현", location_name: "서울", date: "2019/11/1", participate: true },
        { id: 30, host_name: "승현", location_name: "서울", date: "2019/11/1", participate: false },
        { id: 31, host_name: "승현", location_name: "서울", date: "2019/11/1", participate: true },
    ],
    fakeRoomList: [
        { id: 1, host_name: "승현", location_name: "천안", date: "2019/11/1", participate: true },
        { id: 2, host_name: "승현", location_name: "부산", date: "2019/11/1", participate: true },
        { id: 4, host_name: "승현", location_name: "서울", date: "2019/11/1", participate: true },
        { id: 15, host_name: "승현", location_name: "ㅊㅋㅌㅊ", date: "2019/11/23", participate: true },
        { id: 16, host_name: "승현", location_name: "세종", date: "2019/11/23", participate: true },
        { id: 20, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: false },
        { id: 21, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: true },
        { id: 22, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: true },
        { id: 28, host_name: "승현", location_name: "제주도", date: "2019/11/11", participate: true },
        { id: 31, host_name: "승현", location_name: "서울", date: "2019/11/1", participate: true },

    ]
}
